### ISSUE TITLE
Test picks random time zones and random times

### ISSUE THREAD

**Issue by mathieuprog** [hrzndhrn/time_zone_info#33]
Some test depends on `Data.last_year/0` which takes random time zones and random times.
Consequently, the performance result will depend on which time zone and time have been picked, and so the result has no value.
In this case `tz` was first but its position might change after each run depending on the time zone and time randomly picked.

**Comment by NickNeck** [comment]
Hi @mathieuprog 

Yes, you are right. It is hard to compare the implementations because the performance depends on the configuration of each lib and the selected set of data to running the benchmarks. But for each benchmark run, all candidates are using the same set of data. In this case, you can compare the performance using this set of data.

However, I will extend the documentation in the benchmark section and add some fixed data sets. So the comparisons between different benchmarks will be possible.

Thanks for reporting.
Best regards,
Marcus

**Comment by mathieuprog** [comment]
> But for each benchmark run, all candidates are using the same set of data.

I thought that wasn't the case for the test that depends on `Data.last_year/0`. Maybe I missed something. I'll check again later.
